In [14]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

# URL of the website
URL = "https://www.redbus.in"

def initialize_driver():
    driver = webdriver.Chrome()
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get(url)
    time.sleep(5)  # Wait for the page to load

# Function to scrape bus routes
def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text.strip() for route in route_elements]
    return bus_routes_link, bus_routes_name

# Function to scrape bus details
def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)  # Allow the page to load
        
        # Click the "View Buses" button if it exists
        try:
            view_buses_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.CLASS_NAME, "button"))
            )
            driver.execute_script("arguments[0].click();", view_buses_button)
            time.sleep(5)  # Wait for buses to load
            
            # Scroll down to load all bus items
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(5)  # Wait for the page to load more content

            # Find bus item details
            bus_name_elements = driver.find_elements(By.CLASS_NAME, "travels.lh-24.f-bold.d-color")
            bus_type_elements = driver.find_elements(By.CLASS_NAME, "bus-type.f-12.m-top-16.l-color.evBus")
            departing_time_elements = driver.find_elements(By.CLASS_NAME, "dp-time.f-19.d-color.f-bold")
            duration_elements = driver.find_elements(By.CLASS_NAME, "dur.l-color.lh-24")
            reaching_time_elements = driver.find_elements(By.CLASS_NAME, "bp-time.f-19.d-color.disp-Inline")
            star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
            price_elements = driver.find_elements(By.CLASS_NAME, "fare.d-block")

            # Use XPath to handle both seat availability classes
            seat_availability_elements = driver.find_elements(By.XPATH, "//div[contains(@class, 'seat-left m-top-30') or contains(@class, 'seat-left m-top-16')]")

            bus_details = []
            for i in range(len(bus_name_elements)):
                bus_detail = {
                    "Route_Name": route_name,
                    "Route_Link": url,
                    "Bus_Name": bus_name_elements[i].text,
                    "Bus_Type": bus_type_elements[i].text,
                    "Departing_Time": departing_time_elements[i].text,
                    "Duration": duration_elements[i].text,
                    "Reaching_Time": reaching_time_elements[i].text,
                    "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                    "Price": price_elements[i].text,
                    "Seat_Availability": seat_availability_elements[i].text if i < len(seat_availability_elements) else '0'
                }
                bus_details.append(bus_detail)
            return bus_details
        
        except Exception as e:
            print(f"Error occurred while scraping bus details for {url}: {str(e)}")
            return []

    except Exception as e:
        print(f"Error occurred while accessing {url}: {str(e)}")
        return []

# List to hold all bus details
all_bus_details = []

# Function to scrape all pages
def scrape_all_pages():
    for page in range(1, 4):  # There are 3 pages
        try:
            driver = initialize_driver()
            load_page(driver, URL)
            
            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH, f"//div[contains(@class, 'DC_117_pageTabs')][text()='{page}']"))
                )
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)  # Wait for the page to load
            
            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)
            # Iterate over each bus route link and scrape the details
            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)


        except Exception as e:
            print(f"Error occurred while accessing page {page}: {str(e)}")

# Scrape routes and details from all pages
scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(all_bus_details)

# Save the DataFrame to a CSV file
df.to_csv('Telangana_bus_details.csv', index=False)

driver.quit()

Error occurred while accessing page 2: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF784FC9412+29090]
	(No symbol) [0x00007FF784F3E239]
	(No symbol) [0x00007FF784DFB1DA]
	(No symbol) [0x00007FF784E4EFE7]
	(No symbol) [0x00007FF784E4F23C]
	(No symbol) [0x00007FF784E997C7]
	(No symbol) [0x00007FF784E7672F]
	(No symbol) [0x00007FF784E965A2]
	(No symbol) [0x00007FF784E76493]
	(No symbol) [0x00007FF784E409D1]
	(No symbol) [0x00007FF784E41B31]
	GetHandleVerifier [0x00007FF7852E871D+3302573]
	GetHandleVerifier [0x00007FF785334243+3612627]
	GetHandleVerifier [0x00007FF78532A417+3572135]
	GetHandleVerifier [0x00007FF785085EB6+801862]
	(No symbol) [0x00007FF784F4945F]
	(No symbol) [0x00007FF784F44FB4]
	(No symbol) [0x00007FF784F45140]
	(No symbol) [0x00007FF784F3461F]
	BaseThreadInitThunk [0x00007FF9DFCB257D+29]
	RtlUserThreadStart [0x00007FF9E110AF28+40]

Error occurred while accessing page 3: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF784FC9412+29090]
	(No symbol) [0x00007FF784F3E239]
	(No symbol) [0x00007FF784DFB1DA]
	(No symbol) [0x00007FF784E4EFE7]
	(No symbol) [0x00007FF784E4F23C]
	(No symbol) [0x00007FF784E997C7]
	(No symbol) [0x00007FF784E7672F]
	(No symbol) [0x00007FF784E965A2]
	(No symbol) [0x00007FF784E76493]
	(No symbol) [0x00007FF784E409D1]
	(No symbol) [0x00007FF784E41B31]
	GetHandleVerifier [0x00007FF7852E871D+3302573]
	GetHandleVerifier [0x00007FF785334243+3612627]
	GetHandleVerifier [0x00007FF78532A417+3572135]
	GetHandleVerifier [0x00007FF785085EB6+801862]
	(No symbol) [0x00007FF784F4945F]
	(No symbol) [0x00007FF784F44FB4]
	(No symbol) [0x00007FF784F45140]
	(No symbol) [0x00007FF784F3461F]
	BaseThreadInitThunk [0x00007FF9DFCB257D+29]
	RtlUserThreadStart [0x00007FF9E110AF28+40]

NameError: name 'driver' is not defined

In [11]:
pip install selenium

Requirement already satisfied: selenium in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (4.24.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.2)
Requirement already satisfied: trio~=0.17 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from selenium) (0.26.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
df

NameError: name 'df' is not defined

In [15]:
data['Price'] = data['Price'].replace({'INR ': ''}, regex=True).astype(float)

NameError: name 'data' is not defined

In [7]:
pip install pandas sqlalchemy

Requirement already satisfied: pandas in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (2.2.2)
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.34-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from sqlalchemy) (4.11.0)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.5 in c:\users\chakradhar\anaconda3\envs\chakradhar\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading SQLAlchemy-2.0.34-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----------------------------------- ---- 1.8/2.1 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 9.0 MB/s eta 0:00:00
Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl (293 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.34
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sqlalchemy import create_engine
import psycopg2
# Example for PostgreSQL
engine = create_engine('postgresql://username:password@localhost:5432/mydatabase')

# Example for SQLite
# engine = create_engine('sqlite:///mydatabase.db')

In [9]:
pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.9-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Downloading psycopg2-2.9.9-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 11.6 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.9
Note: you may need to restart the kernel to use updated packages.

In [12]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

# URL of the website
URL = "https://www.redbus.in/online-booking/apsrtc/?utm_source=rtchometile"

def initialize_driver():
    driver = webdriver.Chrome()
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get(url)
    time.sleep(5)  # Wait for the page to load

# Function to scrape bus routes
def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text.strip() for route in route_elements]
    return bus_routes_link, bus_routes_name

# Function to scrape bus details
def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)  # Allow the page to load
        
        # Click the "View Buses" button if it exists
        try:
            view_buses_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.CLASS_NAME, "button"))
            )
            driver.execute_script("arguments[0].click();", view_buses_button)
            time.sleep(5)  # Wait for buses to load
            
            # Scroll down to load all bus items
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(5)  # Wait for the page to load more content

            # Find bus item details
            bus_name_elements = driver.find_elements(By.CLASS_NAME, "travels.lh-24.f-bold.d-color")
            bus_type_elements = driver.find_elements(By.CLASS_NAME, "bus-type.f-12.m-top-16.l-color.evBus")
            departing_time_elements = driver.find_elements(By.CLASS_NAME, "dp-time.f-19.d-color.f-bold")
            duration_elements = driver.find_elements(By.CLASS_NAME, "dur.l-color.lh-24")
            reaching_time_elements = driver.find_elements(By.CLASS_NAME, "bp-time.f-19.d-color.disp-Inline")
            star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
            price_elements = driver.find_elements(By.CLASS_NAME, "fare.d-block")

            # Use XPath to handle both seat availability classes
            seat_availability_elements = driver.find_elements(By.XPATH, "//div[contains(@class, 'seat-left m-top-30') or contains(@class, 'seat-left m-top-16')]")

            bus_details = []
            for i in range(len(bus_name_elements)):
                bus_detail = {
                    "Route_Name": route_name,
                    "Route_Link": url,
                    "Bus_Name": bus_name_elements[i].text,
                    "Bus_Type": bus_type_elements[i].text,
                    "Departing_Time": departing_time_elements[i].text,
                    "Duration": duration_elements[i].text,
                    "Reaching_Time": reaching_time_elements[i].text,
                    "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                    "Price": price_elements[i].text,
                    "Seat_Availability": seat_availability_elements[i].text if i < len(seat_availability_elements) else '0'
                }
                bus_details.append(bus_detail)
            return bus_details
        
        except Exception as e:
            print(f"Error occurred while scraping bus details for {url}: {str(e)}")
            return []

    except Exception as e:
        print(f"Error occurred while accessing {url}: {str(e)}")
        return []

# List to hold all bus details
all_bus_details = []

# Function to scrape all pages
def scrape_all_pages():
    for page in range(1, 4):  # There are 3 pages
        try:
            driver = initialize_driver()
            load_page(driver, URL)
            
            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH, f"//div[contains(@class, 'DC_117_pageTabs')][text()='{page}']"))
                )
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)  # Wait for the page to load
            
            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)
            # Iterate over each bus route link and scrape the details
            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)


        except Exception as e:
            print(f"Error occurred while accessing page {page}: {str(e)}")

# Scrape routes and details from all pages
scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(all_bus_details)

# Save the DataFrame to a CSV file
df.to_csv('Telangana_bus_details.csv', index=False)

In [13]:
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3580,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),12:00,06h 00m,18:00,3.9,INR 633,43 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 24256,INDRA(A.C. Seater),12:30,05h 30m,18:00,3.0,INR 528,33 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 9319,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",13:00,06h 20m,19:20,3.5,INR 412,32 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3576,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),13:15,06h 15m,19:30,4.0,INR 633,41 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35154,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",13:40,06h 40m,20:20,3.1,INR 412,26 Seats available
...,...,...,...,...,...,...,...,...,...,...
1495,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...,Matangi Travels,Non A/C Seater / Sleeper (2+1),23:30,06h 05m,05:35,3.8,589,17 Seats available
1496,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...,Maheswari Travels,A/C Sleeper (2+1),23:50,07h 10m,07:00,3.2,INR 999,24 Seats available
1497,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...,Vasavi travels,Non A/C Seater / Sleeper (2+1),23:05,06h 45m,05:50,3.0,INR 649,16 Seats available
1498,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...,ARHA TOURS & TRAVELS PRIVATE LIMITED,A/C Sleeper (2+1),23:59,06h 01m,06:00,2.7,732,16 Seats available
1499,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...,IVR Tours and Travels,Non A/C Seater / Sleeper (2+1),22:46,06h 34m,05:20,0,INR 749,22 Seats available

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         1500 non-null   object
 1   Route_Link         1500 non-null   object
 2   Bus_Name           1500 non-null   object
 3   Bus_Type           1500 non-null   object
 4   Departing_Time     1500 non-null   object
 5   Duration           1500 non-null   object
 6   Reaching_Time      1500 non-null   object
 7   Star_Rating        1500 non-null   object
 8   Price              1500 non-null   object
 9   Seat_Availability  1500 non-null   object
dtypes: object(10)
memory usage: 117.3+ KB

In [19]:
df.to_csv('ap_bus_details.csv', index=False)

In [7]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp312-cp312-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp312-cp312-win_amd64.whl (14.3 MB)
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
    --------------------------------------- 0.3/14.3 MB ? eta -:--:--
    --------------------------------------- 0.3/14.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.3 MB 621.2 kB/s eta 0:00:23
   -- ------------------------------------- 0.8/14.3 MB 780.2 kB/s eta 0:00:18
   --- ------------------------------------ 1.3/14.3 MB 1.2 MB/s eta 0:00:12
   ----- ---------------------------------- 1.8/14.3 MB 1.5 MB/s eta 0:00:09
   ------ --------------------------------- 2.4/14.3 MB 1.7 MB/s eta 0:00:08
   -------- ------------------------------- 3.1/14.3 MB 1.9 MB/s eta 0:00:06
   ---------- ----------------------------- 3.7/14.3 MB 2.0 MB/s eta 0:00:06
   ----------- ---------------------------- 4.2/14.3 MB 2.1 MB/s eta 0:00:05
   ------------- -------------------------- 4.7/14.3 MB 2.1 MB/s eta 0:00:05
   -------------- ------------------------- 5.2/14.3 MB 2.1 MB/s eta 0:00:05
   ---------------- ----------------------- 6.0/14.3 MB 2.3 MB/s eta 0:00:04
   ------------------- -------------------- 6.8/14.3 MB 2.4 MB/s eta 0:00:04
   -------------------- ------------------- 7.3/14.3 MB 2.4 MB/s eta 0:00:03
   ---------------------- ----------------- 8.1/14.3 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 8.7/14.3 MB 2.5 MB/s eta 0:00:03
   -------------------------- ------------- 9.4/14.3 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 10.2/14.3 MB 2.6 MB/s eta 0:00:02
   ------------------------------- -------- 11.3/14.3 MB 2.7 MB/s eta 0:00:02
   ---------------------------------- ----- 12.3/14.3 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 13.4/14.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.3 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 14.3/14.3 MB 2.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd
data = pd.read_csv('ap_bus_details.csv')

In [48]:
data.head()

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 2575,NIGHT RIDER (SEATER CUM SLEEPER),18:55,06h 20m,01:15,3.8,639.0,40 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4916,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:25,06h 50m,02:15,4.2,469.0,27 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 2563,INDRA(A.C. Seater),19:30,05h 55m,01:25,3.3,528.0,34 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 2680,VENNELA (A.C. SLEEPER),19:45,06h 15m,02:00,4.2,839.0,23 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 2573,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),19:45,06h 45m,02:30,3.3,720.0,31 Seats available

In [21]:
print(data.columns)
data.rename(columns={'Seats_Availablility': 'Seats_Availability'}, inplace=True)

Index(['Route_Name', 'Route_Link', 'Bus_Name', 'Bus_Type', 'Departing_Time',
       'Duration', 'Reaching_Time', 'Star_Rating', 'Price',
       'Seat_Availability'],
      dtype='object')

In [22]:
data.isnull()

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
982,False,False,False,False,False,False,False,False,False,False
983,False,False,False,False,False,False,False,False,False,False
984,False,False,False,False,False,False,False,False,False,False
985,False,False,False,False,False,False,False,False,False,False
986,False,False,False,False,False,False,False,False,False,False

In [9]:
import mysql.connector
conn = mysql.connector.connect(user='chakradhar', password='chakradhar123456789', host='localhost', database='bus')
cursor = conn.cursor()

In [10]:
for index, row in data.iterrows():
    cursor.execute("""
        INSERT INTO bus_tsrtc (Route_Name, Route_Link, busname, bustype, Departing_Time, Duration, Reaching_Time, Star_Rating, Price, Seats_Available)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
        (row['Route_Name'], row['Route_Link'], row['Bus_Name'], row['Bus_Type'], row['Departing_Time'], row['Duration'], row['Reaching_Time'], row['Star_Rating'], row['Price'], row['Seat_Availability']))

NameError: name 'data' is not defined

In [57]:
data['Seat_Availability'] = data['Seat_Availability'].replace({'Seats available': ''}, regex=True).astype(str)

In [61]:
conn.commit()
cursor.close()
conn.close()

In [67]:
import streamlit as st
import mysql.connector
import pandas as pd
# Function to connect to SQL and execute queries
def get_filtered_data(bustype, max_price):
    conn = mysql.connector.connect(user='chakradhar', password='Chakri@123', host='localhost', database='bus_db')
    cursor = conn.cursor(dictionary=True)
    
    query = """
    SELECT * FROM bus_apsrtc
    WHERE bustype = %s AND price <= %s
    """
    
    cursor.execute(query, (bustype, max_price))
    data = cursor.fetchall()
    conn.close()
    
    # Convert data to DataFrame
    df = pd.DataFrame(data)
    return df

# Streamlit app
st.title('Bus Routes Data Filter')

# Filter options
bustype = st.selectbox('Select Bus Type', ['Seater', 'Sleeper', 'AC', 'Non-AC'])
max_price = st.slider('Select Maximum Price', 0, 5000, 2000)

# Fetch filtered data
if st.button('Apply Filters'):
    filtered_data = get_filtered_data(bustype, max_price)
    
    # Display filtered data
    st.write(f"Filtered Results for {bustype} buses with price <= {max_price}")
    st.dataframe(filtered_data)

2024-09-11 13:09:09.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 13:09:09.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [78]:
!streamlit run app.py

^C

In [75]:
!pip show streamlit

Name: streamlit
Version: 1.38.0
Summary: A faster way to build and share data apps
Home-page: https://streamlit.io
Author: Snowflake Inc
Author-email: hello@streamlit.io
License: Apache License 2.0
Location: C:\Users\chakradhar\anaconda3\envs\chakradhar\Lib\site-packages
Requires: altair, blinker, cachetools, click, gitpython, numpy, packaging, pandas, pillow, protobuf, pyarrow, pydeck, requests, rich, tenacity, toml, tornado, typing-extensions, watchdog
Required-by:

In [6]:
import streamlit as st
import pandas as pd
from sqlalchemy import create_engine

# Database connection setup
db_user = 'Chakadhar'
db_password = 'chakri@123'

db_port = '3306'  # default MySQL port
db_host = 'localhost'
db_name = 'bus'

# Create a database engine
engine = create_engine(f'mysql+mysqlconnector://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

def load_data():
    query = "SELECT * FROM bus_apsrtc"
    df = pd.read_sql(query, engine)
    return df

# Streamlit app
st.title('Redbus-like Filter App')

# Load data
df = load_data()

# Filter options
st.sidebar.header('Filter Options')
filter_column = st.sidebar.selectbox('Select filter column', df.columns)
unique_values = df[filter_column].unique()
selected_value = st.sidebar.selectbox('Select value', unique_values)

# Filter data based on user selection
filtered_df = df[df[filter_column] == selected_value]

# Display filtered data
st.write(f'Data filtered by {filter_column} = {selected_value}')
st.dataframe(filtered_df)

2024-09-11 16:08:53.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-11 16:08:53.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '123@localhost' (11003)
(Background on this error at: https://sqlalche.me/e/20/4xp6)

In [15]:
from sqlalchemy import create_engine
import pandas as pd

# Replace these values with your actual database credentials
USERNAME = 'chakradhar'
PASSWORD = 'chakri@123'
HOST = 'localhost'
PORT = '3306'
DATABASE = 'bus'

engine=r"C:\\Program Files\\Microsoft SQL Server\\MSSQL16.MSSQLSERVER\\MSSQL\\DATA\\redbus.mdf"

# Test the connection and load data from a table
def load_data():
    try:
        query = 'SELECT * FROM bus_apsrtc'  # Replace 'your_table_name' with your actual table name
        df = pd.read_sql(query, engine)
        print(df.head())
    except Exception as e:
        print(f"An error occurred: {e}")

# Call the function to load data
load_data()

An error occurred: Could not parse SQLAlchemy URL from string 'C:\\Program Files\\Microsoft SQL Server\\MSSQL16.MSSQLSERVER\\MSSQL\\DATA\\redbus.mdf'

In [13]:
pip install sqlalchemy

Collecting sqlalchemy
  Using cached SQLAlchemy-2.0.34-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\chakradhar\anaconda3\envs\chakri\lib\site-packages (from sqlalchemy) (4.11.0)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Downloading greenlet-3.1.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Using cached SQLAlchemy-2.0.34-cp312-cp312-win_amd64.whl (2.1 MB)
Downloading greenlet-3.1.0-cp312-cp312-win_amd64.whl (294 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.1.0 sqlalchemy-2.0.34
Note: you may need to restart the kernel to use updated packages.